name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  S3_BUCKET: portfolio-2025-a
  CF_DIST_ID: EX5MCKL196HD7

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build   # your Next config already exports to 'out/'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::783764607292:role/github-actions-deploy-s3-cloudfront
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller identity
        run: aws sts get-caller-identity

      - name: Ensure build output exists
        run: |
          test -d out || { echo "No 'out' dir found"; exit 1; }
          find out -maxdepth 2 -type f | head -n 50

      - name: Sync static assets (long cache)
        run: |
          aws s3 sync out s3://$S3_BUCKET/ \
            --delete \
            --exclude "*.html" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload HTML (no-cache + correct MIME)
        run: |
          shopt -s nullglob
          for f in $(find out -name "*.html"); do
            key="${f#out/}"
            aws s3 cp "$f" "s3://$S3_BUCKET/$key" \
              --cache-control "no-cache" \
              --content-type "text/html; charset=utf-8"
          done

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
